export interface ITreasure {
    /// <summary>
    /// 名称
    /// </summary>
    Name: string;
    /// <summary>
    /// 博物馆
    /// </summary>
    Museum: string;
    /// <summary>
    /// 描述
    /// </summary>
    Description: string;
    /// <summary>
    /// 朝代
    /// </summary>
    DetailDynasty: string;
    /// <summary>
    /// 种类
    /// </summary>
    Special: string;
    /// <summary>
    /// 出土地
    /// </summary>
    Unearthedplace: string;
    /// <summary>
    /// 作者
    /// </summary>
    Author: string;
    /// <summary>
    /// 临摹者
    /// </summary>
    Reproduction: string;
    /// <summary>
    /// 图片名称
    /// </summary>
    ImageName: string;
}